#!/bin/bash
if [ $# -eq 0 ] ; then
  echo "Starting pyWebServer on port 80"
  python3 pyWebServer.py --host 0.0.0.0 --port 80
else
  echo "Starting pyWebServer on port $1"
  python3 pyWebServer.py --host 0.0.0.0 --port $1
fi
